package uz.ilmnajot.school.enums;

public enum Authority {
    ADD_USER, //ADMIN
    GET_USER,//ALL
    GET_USERS,//ALL
    DELETE_USER,//ADMIN
    UPDATE_USER,//ADMIN
    ADD_ROLE,//ADMIN
    DELETE_ROLE,//ADMIN

    ///NEWS//
    ADD_NEWS,
    DELETE_NEWS,
    UPDATE_NEWS,
    GET_NEWS,
    GET_ALL_NEWS,


    // course
    ADD_COURSE,
    ADD_USER_TO_COURSE,
    DELETE_USER_FROM_COURSE,
    DELETE_COURSE,
    UPDATE_COURSE,

    GET_COURSE,
    GET_COURSE_BY_STUDENT_ID,
    GET_STUDENTS_BY_COURSE_ID,
    GET_ALL_COURSE,

    //*************************test****************//
    ADD_TEST, //ADMIN
    GET_TEST, //USER
    DELETE_TEST,    //ADMIN
    UPDATE_TEST, //ADMIN
    GET_ALL_TEST, //USER
    START_TEST, //USER
    ATTEMPT_TEST,    //USER
    COMPLETE_TEST, //USER

    ADD_QUESTION, //ADMIN
    DELETE_QUESTION, //ADMIN
    UPDATE_QUESTION, //ADMIN
    GET_QUESTION, //USER
    GET_ALL_QUESTION, //USER


}
