package uz.ilmnajot.school.enums;

public enum Authority {
    ADD_USER, //ADMIN
    GET_USER,//ALL
    GET_USERS,//ALL
    DELETE_USER,//ADMIN
    UPDATE_USER,//ADMIN
    ADD_ROLE,//ADMIN
    DELETE_ROLE,//ADMIN

    ///NEWS//
    ADD_NEWS,
    DELETE_NEWS,
    UPDATE_NEWS,
    GET_NEWS,
    GET_ALL_NEWS,


    // course
    ADD_COURSE,
    ADD_USER_TO_COURSE,
    DELETE_USER_FROM_COURSE,
    DELETE_COURSE,
    UPDATE_COURSE,

    GET_COURSE,
    GET_COURSE_BY_STUDENT_ID,
    GET_STUDENTS_BY_COURSE_ID,
    GET_ALL_COURSE,


}
