package uz.ilmnajot.school.enums;

public enum SchoolName {

    SAMARKAND_PRESIDENTIAL_SCHOOL,
    TASHKENT_PRESIDENTIAL_SCHOOL,
    NAMANGAN_PRESIDENTIAL_SCHOOL,
    KHORAZM_PRESIDENTIAL_SCHOOL,
    BUKHORO_PRESIDENTIAL_SCHOOL
}
